
stages:
  - build

jobs:
  include:
  
    # Linux
    - stage: build
      language: cpp
      compiler:
        - clang
        - gcc
      os:
        - linux
      before_install:
        - sudo apt-get -y install ninja-build libomp-dev
        - pip install cmake
      script:
        # Build
        - cmake --version; cmake --log-level=VERBOSE -G "Ninja Multi-Config" -B build; ninja -j12 -C build
        - ninja -j12 -C build -f build-Release.ninja
        # Tests
        - cd build; ctest -VV -j12 -C Debug
      branches:
        only:
          - main
          
    # macOS
    - stage: build
      language: cpp
      compiler:
        - clang
        - gcc
      os:
        - osx
      osx_image: 
        - xcode12
      before_install:
        - HOMEBREW_NO_AUTO_UPDATE=1 brew install ninja
      script:
        - cmake --version; cmake --log-level=VERBOSE -G "Ninja Multi-Config" -B build; ninja -j12 -C build
        - ninja -j12 -C build -f build-Release.ninja
      branches:
        only:
          - main
