 
version: 2.1

executors:
  clang:
    docker:
    - image: cimg/base:2020.01
    environment:
      CC: clang
      CXX: clang++
  gcc:
#    docker:
#    - image: fost/circleci
    environment:
      CC: gcc-10
      CXX: g++-10

jobs:
  build:
    parameters:
      compiler:
        type: executor
      variant:
        type: string
    executor: << parameters.compiler >>
    steps:
      - checkout
#      - run:
#          name: libraries
#          command: |
#            git clone git@github.com:hotkit/fost-boost.git .circleci/boost
#            git clone git@github.com:hotkit/fost-base.git .circleci/fost-base
#            git clone git@github.com:hotkit/fost-crypto.git .circleci/crypto
#            git clone git@github.com:hotkit/cord.git .circleci/cord
#            git clone git@github.com:hotkit/threading.git .circleci/threading
      - run:
          name: cmake
         environment:
           CMAKE_BUILD_TYPE: << parameters.variant >>
          command: cmake -G "Ninja Multi-Config" -B build # cmake -G Ninja -S .circleci -B .circleci
      - run:
          name: ninja
          command: ninja -j12 -C build
#      - run:
#          name: check tests
#          command: ninja -j1 -C .circleci check
#      - run:
#          name: SSL tests
#          command: ninja -j1 -C .circleci fost-internet-ssl-tests

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              compiler: [gcc, clang]
              variant: [Debug, Release]
